### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by hidp123** [balrog-kun/nissan-qashqai-can-info#4]
Hi, on line 605 onwards the table is broken. Looks like an error on line 605 (row 2461 on table). I have edited it and opened a request. You can check if the code is still correct in the correct column. Thanks.

![image](https://github.com/balrog-kun/nissan-qashqai-can-info/assets/84683703/8d3ca8e3-e9ae-406a-b4fd-678b6a719900)

**Comment by balrog-kun** [comment]
Thanks, merged your fix.  Not sure how I introduced that formatting issue.

**Comment by hidp123** [comment]
Thanks.

There are two values in the code, which one is the correct one do you think?

00 00 00 **03** 00 00 00 **3c** 00 00 00 **03** 00 00 00 **7d** 00 00 00 **0d** 00 00 **01** 3f 00 00 00 **0e** 00 00 00 **f8** 00 00 00 04 00 00
00 00 00 **11** 00 00 00 **ce** 00 00 00 **02** 00 00 00 **24** 00 00 00 **02** 00 00 **00** 3f 00 00 00 **11** 00 00 00 **f1** 00 00 00 04 00 00

There is minimal difference between the two.

@balrog-kun

**Comment by balrog-kun** [comment]
Oh yeah, I accidentally added that in one commit.  Let's keep the first value.

Both values are from the same PID but read on different days, I keep some extra values in my local git clone but didn't intend to commit them.
